import type { ExpiringStampBookItem } from "./type";

export function sortByExpiresAt(items: ExpiringStampBookItem[]): ExpiringStampBookItem[] {
  return [...items].sort(
    (a, b) => new Date(a.expiresAt).getTime() - new Date(b.expiresAt).getTime()
  );
}

function addDays(days: number) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}
function pct(current: number, goal: number) {
  return Math.round((current / goal) * 100);
}

export function getExpiringStampBooksMock(): ExpiringStampBookItem[] {
  const goal = 10;
  return [
    {
      id: 101,
      cafe: {
        id: 1,
        name: "카페 위니",
        address: "서울 서대문구 이화여대길 52",
        image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=640",
      },
      round: 2,
      rewardDetail: "스탬프 10개 모으면 아메리카노 한 잔 무료",
      goalCount: goal,
      currentCount: 6,
      progressPercent: pct(6, goal),
      status: "active",
      isCompleted: false,
      expiresAt: addDays(1),
      daysUntilExpiration: 1,
      isExpiringSoon: true,
      previewRewardText: "4회 후 포인트로 자동 환전돼요!",
      canExtend: true,
    },
    {
      id: 102,
      cafe: {
        id: 2,
        name: "블루보틀 연남",
        address: "서울 마포구 연남동 239-20",
        image: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=640",
      },
      round: 1,
      rewardDetail: "스탬프 10개 적립 시 드립커피 1잔 무료",
      goalCount: goal,
      currentCount: 3,
      progressPercent: pct(3, goal),
      status: "active",
      isCompleted: false,
      expiresAt: addDays(2),
      daysUntilExpiration: 2,
      isExpiringSoon: true,
      previewRewardText: "7회 후 포인트로 자동 환전돼요!",
      canExtend: true,
    },
    {
      id: 103,
      cafe: {
        id: 3,
        name: "루프탑 로스터스",
        address: "서울 용산구 후암동 394-7",
        image: "https://images.unsplash.com/photo-1445077100181-a33e9ac94db0?w=640",
      },
      round: 3,
      rewardDetail: "10개 모으면 라떼 업그레이드",
      goalCount: goal,
      currentCount: 9,
      progressPercent: pct(9, goal),
      status: "active",
      isCompleted: false,
      expiresAt: addDays(3),
      daysUntilExpiration: 3,
      isExpiringSoon: true,
      previewRewardText: "1회 후 포인트로 자동 환전돼요!",
      canExtend: false,
    },
    {
      id: 104,
      cafe: {
        id: 4,
        name: "어반 그라인더",
        address: "서울 성동구 성수이로 78",
        image: "https://images.unsplash.com/photo-1498804103079-a6351b050096?w=640",
      },
      round: 1,
      rewardDetail: "10개 모으면 디저트 1개 무료",
      goalCount: goal,
      currentCount: 1,
      progressPercent: pct(1, goal),
      status: "active",
      isCompleted: false,
      expiresAt: addDays(4),
      daysUntilExpiration: 4,
      isExpiringSoon: true,
      previewRewardText: "9회 후 포인트로 자동 환전돼요!",
      canExtend: true,
    },
    {
      id: 105,
      cafe: {
        id: 5,
        name: "하루커피",
        address: "서울 광진구 자양로 45",
        image: "https://images.unsplash.com/photo-1432107294469-414527cb5c65?w=640",
      },
      round: 2,
      rewardDetail: "스탬프 10개 = 아메리카노 1잔",
      goalCount: goal,
      currentCount: 5,
      progressPercent: pct(5, goal),
      status: "active",
      isCompleted: false,
      expiresAt: addDays(5),
      daysUntilExpiration: 5,
      isExpiringSoon: true,
      previewRewardText: "5회 후 포인트로 자동 환전돼요!",
      canExtend: true,
    },
    {
      id: 106,
      cafe: {
        id: 6,
        name: "브라운빈",
        address: "서울 마포구 독막로 33",
        image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=640",
      },
      round: 1,
      rewardDetail: "10개 모으면 콜드브루 1잔 무료",
      goalCount: goal,
      currentCount: 8,
      progressPercent: pct(8, goal),
      status: "active",
      isCompleted: false,
      expiresAt: addDays(6),
      daysUntilExpiration: 6,
      isExpiringSoon: true,
      previewRewardText: "2회 후 포인트로 자동 환전돼요!",
      canExtend: false,
    },
    {
      id: 107,
      cafe: {
        id: 7,
        name: "테라스 라운지",
        address: "서울 강남구 테헤란로 201",
        image: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=640",
      },
      round: 4,
      rewardDetail: "10개 모으면 샷 추가 무료",
      goalCount: goal,
      currentCount: 10,
      progressPercent: pct(10, goal),
      status: "active",
      isCompleted: true,
      expiresAt: addDays(1),
      daysUntilExpiration: 1,
      isExpiringSoon: true,
      previewRewardText: "오늘 포인트로 자동 환전돼요!",
      canExtend: false,
    },
    {
      id: 108,
      cafe: {
        id: 8,
        name: "커피리브레",
        address: "서울 마포구 성미산로 21",
        image: "https://images.unsplash.com/photo-1512568400610-62da28bc8a13?w=640",
      },
      round: 2,
      rewardDetail: "10개 적립 시 메뉴 1종 50% 할인",
      goalCount: goal,
      currentCount: 4,
      progressPercent: pct(4, goal),
      status: "active",
      isCompleted: false,
      expiresAt: addDays(2),
      daysUntilExpiration: 2,
      isExpiringSoon: true,
      previewRewardText: "6회 후 포인트로 자동 환전돼요!",
      canExtend: true,
    },
    {
      id: 109,
      cafe: {
        id: 9,
        name: "골목카페",
        address: "서울 종로구 자하문로 22",
        image: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=640",
      },
      round: 1,
      rewardDetail: "10개 모으면 바닐라라떼 1잔 무료",
      goalCount: goal,
      currentCount: 2,
      progressPercent: pct(2, goal),
      status: "active",
      isCompleted: false,
      expiresAt: addDays(7),
      daysUntilExpiration: 7,
      isExpiringSoon: true,
      previewRewardText: "8회 후 포인트로 자동 환전돼요!",
      canExtend: true,
    },
    {
      id: 110,
      cafe: {
        id: 10,
        name: "미드나잇 브루",
        address: "서울 서초구 강남대로 321",
        image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=640",
      },
      round: 3,
      rewardDetail: "10개 모으면 드립백 증정",
      goalCount: goal,
      currentCount: 7,
      progressPercent: pct(7, goal),
      status: "active",
      isCompleted: false,
      expiresAt: addDays(3),
      daysUntilExpiration: 3,
      isExpiringSoon: true,
      previewRewardText: "3회 후 포인트로 자동 환전돼요!",
      canExtend: true,
    },
  ];
}