import type { CafeListResponse } from './type';

export const cafeListMockResponse: CafeListResponse = {
  resultType: 'SUCCESS',
  error: null,
  success: {
    fromNLP: false,
    data: [
      {
        id: 101,
        name: '로스터리 카페 A',
        address: '서울특별시 강남구 역삼동 123-1',
        keywords: ['스페셜티', '조용한', '와이파이'],
        latitude: 37.5037,
        longitude: 127.0276,
        region1DepthName: '서울특별시',
        region2DepthName: '강남구',
        region3DepthName: '역삼동',
        createdAt: '2025-07-20T12:34:56Z',
        photos: [{ id: '101-a', photoUrl: '/sample/a.jpg' }],
        bookmarkedBy: [{ id: 11 }, { id: 23 }],
        isBookmarked: false,
        isStamped: true,
        distance: 120,
      },
      {
        id: 102,
        name: '브루잉 카페 B',
        address: '서울특별시 강남구 역삼동 45-7',
        keywords: ['브루잉', '디저트맛집'],
        latitude: 37.5029,
        longitude: 127.0291,
        region1DepthName: '서울특별시',
        region2DepthName: '강남구',
        region3DepthName: '역삼동',
        createdAt: '2025-07-18T09:10:00Z',
        photos: [{ id: '102-a', url: '/sample/b.jpg' }, { id: '102-b', photoUrl: '/sample/b2.jpg' }],
        bookmarkedBy: [],
        isBookmarked: false,
        isStamped: false,
        distance: 260,
      },
      {
        id: 103,
        name: '스페셜티 랩 C',
        address: '서울특별시 강남구 역삼동 201-3',
        keywords: ['노트북석', '콘센트많음', '조용한'],
        latitude: 37.5046,
        longitude: 127.0265,
        region1DepthName: '서울특별시',
        region2DepthName: '강남구',
        region3DepthName: '역삼동',
        createdAt: '2025-07-15T15:20:00Z',
        photos: [{ id: '103-a', photoUrl: '/sample/c.jpg' }],
        bookmarkedBy: [{ id: 7 }],
        isBookmarked: true,
        isStamped: false,
        distance: 310,
      },
      {
        id: 104,
        name: '테라스 커피 D',
        address: '서울특별시 강남구 역삼동 88-9',
        keywords: ['테라스', '반려견동반'],
        latitude: 37.5008,
        longitude: 127.0289,
        region1DepthName: '서울특별시',
        region2DepthName: '강남구',
        region3DepthName: '역삼동',
        createdAt: '2025-07-12T08:00:00Z',
        photos: [{ id: '104-a', url: '/sample/d.jpg' }],
        bookmarkedBy: [],
        isBookmarked: false,
        isStamped: true,
        distance: 540,
      },
      {
        id: 105,
        name: '디저트 카페 E',
        address: '서울특별시 강남구 역삼동 310-2',
        keywords: ['디저트', '포토존'],
        latitude: 37.5062,
        longitude: 127.0253,
        region1DepthName: '서울특별시',
        region2DepthName: '강남구',
        region3DepthName: '역삼동',
        createdAt: '2025-07-10T11:45:00Z',
        photos: [{ id: '105-a', photoUrl: '/sample/e.jpg' }],
        bookmarkedBy: [{ id: 31 }],
        isBookmarked: false,
        isStamped: false,
        distance: 780,
      },
      {
        id: 106,
        name: '라떼하우스 F',
        address: '서울특별시 강남구 역삼동 512-6',
        keywords: ['라떼맛집', '아늑함'],
        latitude: 37.5052,
        longitude: 127.0304,
        region1DepthName: '서울특별시',
        region2DepthName: '강남구',
        region3DepthName: '역삼동',
        createdAt: '2025-07-08T10:00:00Z',
        photos: [{ id: '106-a', url: '/sample/f.jpg' }],
        bookmarkedBy: [],
        isBookmarked: false,
        isStamped: false,
        distance: 950,
      },
    ],
    nextCursor: 106, // 다음 페이지 커서(없으면 null)
    hasMore: true,
  },
};

// 빈 결과 목 (필요 시)
export const cafeListEmptyMockResponse: CafeListResponse = {
  resultType: 'SUCCESS',
  error: null,
  success: {
    fromNLP: false,
    data: [],
    nextCursor: null,
    hasMore: false,
  },
};
